# Легкая модель для проверки работоспособности
model:
  name: "Light Stocks"
  n_stocks: 100  # Кол-во случайных компаний, которые будут подаваться во время обучения
  n_days: 7  # Кол-во дней эксперимента
  n_days_history: 60  # Кол-во учтенных дней акций
  variance: 0.1  # Дисперсия выручки для выхода из эпизода
  n_tries: 50  # Кол-во последних попыток, учетиываемых в дисперсии для выхода из эпизода
  start_capital: 10000  # Начальный капитал
  comission_on_buy: 0.001  # Комиссия брокера при покупке
  comission_on_sale: 0.001  # Комиссия брокера при продаже
  comission_on_new_day: 0.001  # Доп Комиссия следующего дня